# Generated by Django 6.0.2 on 2026-03-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parkinglot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='parkinglot_image',
            field=models.ImageField(blank=True, null=True, upload_to='parkinglot_images/'),
        ),
    ]
