# Generated by Django 6.0.2 on 2026-03-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parkinglot', '0002_parkinglot_parkinglot_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='parkinglot_image',
            field=models.ImageField(blank=True, null=True, upload_to='Parkinglot_images/'),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
