# Generated by Django 6.0.2 on 2026-04-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parkinglot', '0003_alter_parkinglot_parkinglot_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='reservation',
            name='vehicle_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
