# Generated by Django 6.0.2 on 2026-04-15 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parkinglot', '0004_remove_reservation_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('truck', 'Truck'), ('suv', 'SUV')], default='car', max_length=20),
        ),
    ]
