# Generated by Django 6.0.2 on 2026-02-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('owner', 'owner'), ('user', 'user')], default='user', max_length=10),
        ),
    ]
